// <auto-generated />
using System;
using FamilySync.Registry.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilySync.Registry.Migrations
{
    [DbContext(typeof(RegistryContext))]
    [Migration("20231027082936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FamilySync.Registry.Models.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("FamilySync.Registry.Models.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.HasKey("MemberId", "FamilyId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Memebers");
                });

            modelBuilder.Entity("FamilySync.Registry.Models.Entities.FamilyMember", b =>
                {
                    b.HasOne("FamilySync.Registry.Models.Entities.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Family");
                });

            modelBuilder.Entity("FamilySync.Registry.Models.Entities.Family", b =>
                {
                    b.Navigation("FamilyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
